service: serverless

provider:
  name: aws
  runtime: nodejs12.x

functions:
  helloWorld:
    handler: src/handler.lambdaHandler
    events:
      - http:
          path: hello-world
          method: get
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - node_modules/**/*
  include:
    handler.ts